# 과제2
추정된 회귀계수를 구하는 함수 구현하기 (행렬곱을 이용해서 간단하게 , numpy 사용 , 5 줄 이하)



**input**:
data_x (독립변수 행렬 데이터 ), data_y (종속변수 벡터 데이터)



**output**:
추정된 회귀계수 (벡터)

In [35]:
import numpy as np
from numpy.linalg import inv 

def estimate_beta(x, y):
    beta_hat = inv(x.transpose().dot(x)).dot(x.transpose()).dot(y)
    return beta_hat

In [36]:
#x행렬에 intercept를 추가해야함
x = np.array([ [1, 0, 1],
               [1, 2, 3],
               [1, 3, 8]]) #3x3
y = np.transpose(np.array([1, 3, 7])) #3x1

In [37]:
x

array([[1, 0, 1],
       [1, 2, 3],
       [1, 3, 8]])

In [38]:
y

array([1, 3, 7])

In [39]:
estimate_beta(x,y)

array([0.25, 0.25, 0.75])

In [40]:
#sklearn은 디폴트로 intercept가 fit되므로, 데이터에 intercept가 포함된 경우는 fit_intercept=False로 해야함

In [41]:
from sklearn.linear_model import LinearRegression

In [42]:
reg = LinearRegression(fit_intercept=False).fit(x, y)

In [43]:
reg.coef_

array([0.25, 0.25, 0.75])